segments:
  upper_rhine:
    label: "Upper Rhine"
    stations:
      - BASEL-RHEINHALLE
      - RHEINWEILER
      - BREISACH
      - IFFEZHEIM
      - MAXAU

  middle_rhine:
    label: "Middle Rhine"
    stations:
      - SPEYER
      - MANNHEIM
      - WORMS
      - MAINZ
      - BINGEN
      - KAUB
      - SANKT GOAR
      - KOBLENZ

  lower_rhine:
    label: "Lower Rhine"
    stations:
      - BONN
      - KÖLN
      - DÜSSELDORF
      - DUISBURG-RUHRORT
      - WESEL
      - REES
      - EMMERICH
      - LOBITH