pegelonline:
  schedule: "0 */3 * * *"
  path: "/stations.json?includeTimeseries=true"
  priority_gauges:
    - Kaub
    - Duisburg-Ruhrort
    - Karlsruhe-Maxau
    - Koblenz

dwd:
  schedule: "30 */6 * * *"
  product_hint: "hourly climate / precipitation / temperature"

