low_water_thresholds_cm:
  BASEL-RHEINHALLE: 501
  MAXAU: 372
  SPEYER: 237
  MANNHEIM: 155
  WORMS: 68
  MAINZ: 171
  OESTRICH: 92
  BINGEN: 97
  KAUB: 77
  KOBLENZ: 77
  BONN: 142
  KÖLN: 139
  DÜSSELDORF: 91
  DUISBURG-RUHRORT: 227
  WESEL: 174
  REES: 118
  EMMERICH: 74
  LOBITH: 733
  PANNERDENSE KOP: 700